Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/02/2026
Var
// Seção de Declarações das variáveis 
numero,divisao: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("escreva o numero: ")
leia(numero)
divisao<- numero mod 2
escreval("o resultado e: ",divisao )


Fimalgoritmo