Algoritmo "exercicio 8"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/02/2026
Var
// Seção de Declarações das variáveis 
resultado, n1, n2: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("digite o primeiro numero: ")
leia(n1)
escreval("digite o segundo numero: ")
leia(n2)
resultado<- (n1 ^ n2)
escreval("o resultado e: ", resultado)
Fimalgoritmo