Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/02/2026
Var
// Seção de Declarações das variáveis 
n1, antecessor, sucessor: inteiro

Inicio

escreva("digite um numero inteiro: ")
leia(n1)
antecessor <- n1 - 1
sucessor <- n1 + 1
escreva("antecessor: ", antecessor)
escreval(" sucessor: ", sucessor)


Fimalgoritmo