Algoritmo "exercicio 11"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/02/2026
Var
// Seção de Declarações das variáveis 
 media: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite a média do aluno: ")
leia(media)

se media >= 7 entao
escreva("Aluno APROVADO!")
senao
escreva("Aluno REPROVADO!")
fimse

Fimalgoritmo