Algoritmo "exercicio 2 "
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/02/2026
Var
// Seção de Declarações das variáveis 
soma, n1, n2:inteiro

Inicio
escreva("digite o primeiro numero: ")
leia(n1)
escreva("digite o segundo numero: ")
leia(n2)
soma <- n1 + n2
escreva("resultado: ", soma)





Fimalgoritmo